import gumroad
from base64 import b64encode

def create_gumroad_product(slug, title, price_cents=200, file_path=None):
    gr = gumroad.Gumroad(GUMROAD_TOKEN)
    r = gr.post("products", json={
        "product": {
            "name": title,
            "url": slug,
            "price": price_cents,
            "description": "Instant digital download. Generated by AI.",
            "custom_permalink": slug,
            "max_purchase_count": None,
            "published": True,
        }
    })
    product_id = r.json()["product"]["id"]
    if file_path:
        gr.put(f"products/{product_id}/files", files={"file": open(file_path, "rb")})
    return f"https://gum.co/{slug}"